# Generated by Django 3.2 on 2023-11-30 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Author ismi')),
                ('bio', models.TextField(verbose_name='Yozuvchi haqida')),
                ('image', models.ImageField(upload_to='img/', verbose_name='Rasm')),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Yozuvchi',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Categoriya nomi')),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=399, verbose_name='Kitob nomi')),
                ('body', models.TextField(verbose_name='Kitob haqida')),
                ('price', models.CharField(max_length=20, verbose_name='Kitob narxi')),
                ('image', models.ImageField(upload_to='book/', verbose_name='Kitob rasmi')),
                ('created_at', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Kitob_',
            },
        ),
    ]
